name: Github Actions Test

on:
   pull_request:
   push:
       branches:
        - master
        - develop

jobs:
   test:
     name: Running Units Test
     runs-on: ubuntu-lastest

   steps:
    - uses: actions/checkout@v1
    - name: Use Nose.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Test
      run: npm test
        